import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {loadSource} from '../../../tests/load-source.mjs';
const {default:pack}=loadSource('src/campaign/life/day05.ts');
const {default:explore}=loadSource('src/campaign/exploration/day05.ts');
const {default:outside}=loadSource('src/campaign/worlds/day05.ts');
const {buildWorldNavigation,allWorldFlags}=loadSource('src/campaign/worldGeometry.ts');
const {LEVELS}=loadSource('src/campaign/levels.ts');
const results=[];function check(name,f){try{f();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.message});}}
function route(nav,a,b){assert.ok(nav.isWalkable(a),'start not walkable');assert.ok(nav.isWalkable(b),'authored stance not walkable');const path=nav.route(a,b,()=>false,0);assert.ok(path.length,'empty path');let last=a;for(const p of path){assert.ok(nav.visible(last,p),'segment crosses obstacle');last=p;}assert.ok(Math.hypot(last.x-b.x,last.y-b.y)<1,'route snaps away from stance');}
const all=[...pack.outside,...pack.inside];
check('IDs, budgets, lifecycle and physical binding',()=>{assert.equal(new Set(all.map(n=>n.id)).size,all.length);const sharedIds=all.filter(n=>n.sharedDiscovery).map(n=>n.sharedDiscovery);assert.equal(new Set(sharedIds).size,sharedIds.length);for(const scene of [pack.outside,pack.inside]){assert.ok(scene.length>=6);for(const k of ['container','gather','inspect'])assert.ok(scene.filter(n=>n.kind===k).length>=2,k);}for(const n of all){assert.ok(n.id.startsWith('d05-life-'));assert.ok(n.baked.length>=3);assert.ok(n.visual.support.length>10);assert.ok(Number.isFinite(n.visual.depth));assert.ok(n.description&&n.emptyText);if(n.kind==='inspect')assert.ok(!n.lootTable);else assert.ok(['salvage','nature','pantry','mineral','pocket','cloth','herbs','fruit','stone','wood','paper','tea'].includes(n.lootTable));if(n.kind==='gather')assert.ok(n.renewSeconds>=180);for(const p of n.baked)assert.ok(p.x>=0&&p.x<=1600&&p.y>=0&&p.y<=900);if(n.sharedDiscovery){const source=[...explore.outside,...explore.room.nodes].find(d=>d.id===n.sharedDiscovery);assert.ok(source,n.sharedDiscovery);assert.deepEqual(n.approach,source.approach);assert.deepEqual(n.baked,source.baked);assert.deepEqual(n.visual,source.visual);}}});
for(const [scene,nodes,world] of [['outside',pack.outside,outside],['inside',pack.inside,explore.room.world]])for(const [state,flags] of [['initial',new Set()],['complete',allWorldFlags(world,LEVELS[4].puzzles.map(p=>p.id))]]){const nav=buildWorldNavigation(world,flags);for(const n of nodes)check(`${scene}/${state}/${n.id}`,()=>route(nav,world.spawn,n.approach));const targets=scene==='outside'?[...Object.entries(world.approaches).map(([id,approach])=>({id,approach})),{id:'room-door',approach:explore.room.entry.approach},...explore.outside]:[{id:'return',approach:world.approaches.exit},...explore.room.nodes];for(const n of targets)check(`${scene}/${state}/regression/${n.id}`,()=>route(nav,world.spawn,n.approach));}
const p=(x,y)=>({x:x*1600/1672,y:y*900/941});
for(const [scene,world,points] of [['outside',outside,[[1266,345],[1290,310],[270,545],[580,650],[880,620]]],['inside',explore.room.world,[[210,410],[530,310],[670,490],[880,250],[1100,360],[1160,409],[1520,410],[1300,585],[1170,590],[1450,590],[160,640],[380,685]]]]){const nav=buildWorldNavigation(world,new Set());for(const [x,y] of points)check(`${scene}/negative/${x},${y}`,()=>assert.equal(nav.isWalkable(scene==='inside'?p(x,y):{x,y}),false));}
const counts=Object.fromEntries(['outside','inside'].map(scene=>[scene,{total:pack[scene].length,...Object.fromEntries(['container','gather','inspect'].map(k=>[k,pack[scene].filter(n=>n.kind===k).length]))}]));
const result={day:5,counts,checks:results.length,passed:results.filter(r=>r.status==='PASS').length,results,limitations:['Data/navigation validation only; runtime economy and combined sharedDiscovery UI must be integrated centrally.','No new bitmap assets or afterArt. Lidded tasting jars are opened and reclosed; only the personal allocation is exhausted. Drawers close again after paper collection.']};
writeFileSync('design/life-015/day05/audit-results.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(counts));for(const r of results.filter(r=>r.status==='FAIL'))console.log(r);console.log(`${result.passed}/${result.checks} passed`);if(result.passed!==result.checks)process.exitCode=1;
