import type { LevelDefinition, Palette, Point, Rect } from "./types";

const palettes: Record<string, Palette> = {
  rain: { sky: "#8295a5", ground: "#667682", groundAlt: "#52626e", path: "#8e969b", pathEdge: "#384b58", water: "#4e8ea3", accent: "#ffd66b", accentSoft: "#fff0b6", shadow: "#263946" },
  office: { sky: "#151b2d", ground: "#30364a", groundAlt: "#242a3c", path: "#596078", pathEdge: "#171d2f", water: "#3f5875", accent: "#ffbd69", accentSoft: "#ffe3ad", shadow: "#101522" },
  flower: { sky: "#8ed6e8", ground: "#86c86f", groundAlt: "#65ad64", path: "#efcf9b", pathEdge: "#bd9866", water: "#50acc4", accent: "#fff077", accentSoft: "#fff8bb", shadow: "#416a58" },
  falls: { sky: "#74c8e5", ground: "#65b783", groundAlt: "#438f71", path: "#e6d4a5", pathEdge: "#9f865d", water: "#32a9d0", accent: "#ff8fc6", accentSoft: "#ffd5e9", shadow: "#315f68" },
  autumn: { sky: "#efb76d", ground: "#bc9657", groundAlt: "#967244", path: "#e8c993", pathEdge: "#8c603b", water: "#4f9ca3", accent: "#ffd25d", accentSoft: "#ffe9a2", shadow: "#66462f" },
  storm: { sky: "#5f7185", ground: "#67805e", groundAlt: "#4d644d", path: "#a59a7b", pathEdge: "#595343", water: "#477f96", accent: "#ffe55c", accentSoft: "#fff3a8", shadow: "#34424a" },
  snow: { sky: "#889ab3", ground: "#d4e6eb", groundAlt: "#b8d0d9", path: "#eef7f7", pathEdge: "#839caa", water: "#6c9fbb", accent: "#ffb66e", accentSoft: "#ffe0b9", shadow: "#526a83" },
  cave: { sky: "#17192c", ground: "#292947", groundAlt: "#20203b", path: "#494568", pathEdge: "#17152b", water: "#295f83", accent: "#69f0d0", accentSoft: "#c5fff1", shadow: "#101020" },
};

const rect = (x: number, y: number, width: number, height: number): Rect => ({ x, y, width, height });
const point = (x: number, y: number): Point => ({ x, y });

export const LEVELS: LevelDefinition[] = [
  {
    id: "rain-commute",
    day: 1,
    name: "暴雨通勤",
    subtitle: "别让赶路盖过了观察",
    stamp: "好",
    environment: "rain-city",
    intro: "一夜暴雨淹了旧城区。去车站报平安，但每一条看似更快的路都可能正在变化。",
    goal: "抵达车站，并把沿途四处安全信息重新拼成报平安口令。",
    ending: "站台灯亮起来。你发出三个字：我到了。",
    code: "7249",
    finalSymbolOrder: ["闸", "车", "灯", "站"],
    palette: palettes.rain,
    weatherIcon: "☂",
    startTime: "07:18",
    playerStart: point(125, 765),
    exit: point(1470, 140),
    route: [point(125, 765), point(335, 690), point(555, 715), point(710, 560), point(920, 575), point(1040, 390), point(1260, 330), point(1470, 140)],
    puzzles: [
      {
        id: "drain-order", kind: "sequence", icon: "▥", symbol: "闸", title: "被堵住的雨水篦", position: point(345, 690),
        story: "积水已经碰到路边配电箱。清理顺序错了，会先把自己置于危险里。",
        prompt: "按安全顺序处理积水点。",
        evidence: ["配电箱底部有水痕，侧面的红色拉杆仍在“通”。", "落叶压住了篦盖，警示牌倒在干燥的人行道上。"],
        instruction: "依次选择四个动作；顺序错误会重新开始。",
        options: ["切断路边电源", "移开湿落叶", "掀开雨水篦", "立起警示牌"],
        solution: ["切断路边电源", "立起警示牌", "移开湿落叶", "掀开雨水篦"],
        rewardDigit: "7", rewardItem: "干燥的绝缘手套", solvedText: "积水开始下降，篦盖内侧露出“闸＝7”。", wrongFeedback: "水和电还没有被隔开。先让现场安全，再动手疏通。",
        hints: ["红色拉杆比落叶更值得先看。", "先断电并提醒路人，再接触积水附近的东西。", "顺序是：断电 → 立警示牌 → 移落叶 → 开雨水篦。"],
      },
      {
        id: "bus-route", kind: "choice", icon: "▤", symbol: "车", title: "停摆的电子站牌", position: point(695, 560), requires: ["drain-order"],
        story: "三条接驳线只剩一条能穿过涨水后的城区。站牌还保存着最后一次路况广播。",
        prompt: "根据高程与封路信息，选出仍可通行的接驳线。",
        evidence: ["广播：河东路低于警戒水位 0.4 米；隧道口封闭。", "2 路经过高架、医院坡道与北广场；7 路经过隧道；9 路经过河东路。"],
        instruction: "选择一条不会经过封闭或低洼路段的线路。",
        options: ["2 路高架接驳", "7 路隧道接驳", "9 路河东接驳"], solution: ["2 路高架接驳"],
        rewardDigit: "2", rewardItem: "接驳车票", solvedText: "站牌吐出一张旧票：“车＝2”。", wrongFeedback: "这条线路会经过广播中点名的危险路段。",
        hints: ["把广播里的两个禁区圈出来。", "隧道和河东路都不能走，只剩经过高处的线路。", "选择 2 路高架接驳。"],
      },
      {
        id: "signal-cycle", kind: "pattern", icon: "◈", symbol: "灯", title: "失灵的过街信号", position: point(1035, 390), requires: ["bus-route"],
        story: "信号灯在重启后丢失了最后三个状态。路口监控留下了循环规律。",
        prompt: "补全下一轮行人信号。",
        evidence: ["记录依次为：停、停、看、走｜停、停、看、走。", "控制器提示：每四拍循环，第三拍确认左右，第四拍才放行。"],
        instruction: "点击三个格子切换状态，填入下一轮的前三拍。",
        options: ["停", "看", "走"], solution: ["停", "停", "看"], slots: 3,
        rewardDigit: "4", rewardItem: "反光安全夹", solvedText: "行人灯恢复稳定，灯罩背面写着“灯＝4”。", wrongFeedback: "循环没有对齐。把竖线当作一轮的边界。",
        hints: ["每四拍会完整重复一次。", "下一轮应从前一轮的开头重新开始。", "三个格子依次是：停、停、看。"],
      },
      {
        id: "platform-lock", kind: "number", icon: "▣", symbol: "站", title: "站务应急柜", position: point(1260, 325), requires: ["signal-cycle"],
        story: "应急柜里有开往安全站台的钥匙，柜门密码是仍可用的站台编号。",
        prompt: "算出唯一满足广播条件的站台编号。",
        evidence: ["广播：单号站台停运；6 号积水；编号大于 7。", "本站只有 1—9 号站台。"],
        instruction: "输入一位站台编号。",
        options: [], solution: ["8"],
        rewardDigit: "9", rewardItem: "站台铜钥匙", solvedText: "8 号站台钥匙旁刻着“站＝9”。", wrongFeedback: "这个编号违反了至少一条广播条件。",
        hints: ["先排除所有单数。", "偶数里再排除 6，并且编号必须大于 7。", "唯一答案是 8 号站台。"],
      },
    ],
    sideTasks: [
      { id: "help-cat", icon: "猫", title: "纸箱里的小猫", position: point(535, 720), prompt: "把纸箱挪到屋檐下。", completeText: "小猫抖掉雨水，冲你轻轻叫了一声。" },
      { id: "call-home", icon: "☎", title: "借来的电话", position: point(915, 570), prompt: "告诉家里你正在走安全路线。", completeText: "电话那头只说：慢一点，不要急。" },
    ],
    hazards: [
      { id: "live-water", title: "带电积水", rect: rect(520, 585, 150, 100), period: 8, warningFrom: 2.5, activeFrom: 5.2, warning: "水面出现蓝白电弧", lesson: "积水靠近电力设施时，不要涉水；先断电并绕行。", color: "#8fe8ff" },
      { id: "falling-sign", title: "松动招牌", rect: rect(1070, 285, 125, 95), period: 9, warningFrom: 3.8, activeFrom: 6.5, warning: "招牌吱呀摇晃，碎屑开始掉落", lesson: "大风暴雨时远离松动招牌和临时搭建物。", color: "#ffd25f" },
    ],
    landmarks: [
      { title: "老公寓", icon: "⌂", position: point(115, 710), size: 75 }, { title: "早餐铺", icon: "☕", position: point(300, 820), size: 56 },
      { title: "高架桥", icon: "桥", position: point(760, 660), size: 72 }, { title: "北站", icon: "站", position: point(1480, 92), size: 90 },
    ],
    blockers: [rect(0, 0, 70, 900), rect(1530, 0, 70, 900), rect(420, 390, 170, 95), rect(850, 165, 180, 100)],
  },
  {
    id: "late-office",
    day: 2,
    name: "深夜加班",
    subtitle: "完成工作不等于忽略身体",
    stamp: "好",
    environment: "night-office",
    intro: "写字楼已经熄了一半的灯。打印最后一份文件，带上仍没回家的同事，从安全楼梯离开。",
    goal: "恢复四处安全设施，判断真正可用的撤离路线。",
    ending: "凌晨的风吹散烟味。你关掉工作群，第一次说：先回家。",
    code: "1863",
    finalSymbolOrder: ["电", "铃", "梯", "门"],
    palette: palettes.office,
    weatherIcon: "☾",
    startTime: "23:42",
    playerStart: point(135, 135),
    exit: point(1450, 760),
    route: [point(135, 135), point(395, 145), point(395, 330), point(690, 330), point(690, 585), point(1010, 585), point(1010, 745), point(1450, 760)],
    puzzles: [
      {
        id: "breaker", kind: "choice", icon: "⚡", symbol: "电", title: "发热的配电箱", position: point(390, 145),
        story: "茶水间传来焦糊味。四个分闸里只有一个同时满足标签和电流记录。",
        prompt: "找出应立即断开的分闸。",
        evidence: ["打印机 2A、走廊灯 1A、茶水间 9A、电梯待机 2A。", "告示：夜间任何支路超过 6A 都应断开检查。"],
        instruction: "选择异常支路。",
        options: ["A 打印机", "B 走廊灯", "C 茶水间", "D 电梯"], solution: ["C 茶水间"],
        rewardDigit: "1", rewardItem: "绝缘配电钥匙", solvedText: "温度开始下降，分闸标签后露出“电＝1”。", wrongFeedback: "这个支路的夜间电流没有超过警戒线。",
        hints: ["比较每个支路与 6A。", "只有一个读数大于 6A。", "断开 C 茶水间。"],
      },
      {
        id: "alarm", kind: "sequence", icon: "◎", symbol: "铃", title: "静音的火警控制器", position: point(395, 330), requires: ["breaker"],
        story: "轻烟从吊顶渗出，控制器被误设为静音。面板旁贴着处置流程。",
        prompt: "恢复报警并组织撤离。",
        evidence: ["流程图的箭头：确认火情 → 触发报警 → 提醒同层人员 → 走安全楼梯。", "红字：不得先乘电梯，不得独自寻找火源。"],
        instruction: "按流程选择四步。",
        options: ["确认烟雾来源", "按下火警按钮", "通知同层人员", "进入安全楼梯"], solution: ["确认烟雾来源", "按下火警按钮", "通知同层人员", "进入安全楼梯"],
        rewardDigit: "8", rewardItem: "防烟面罩", solvedText: "报警铃恢复，检修签上写着“铃＝8”。", wrongFeedback: "处置顺序会让其他人更晚知道危险。",
        hints: ["先确认，再让整层楼知道。", "报警之后再组织人员进入安全楼梯。", "确认 → 报警 → 通知 → 楼梯。"],
      },
      {
        id: "stair-map", kind: "pattern", icon: "▧", symbol: "梯", title: "缺角的疏散图", position: point(690, 585), requires: ["alarm"],
        story: "烟让东侧通道不可见。疏散图用箭头重复标出绕开中庭的路径。",
        prompt: "补全缺失的三个方向。",
        evidence: ["完整段为：右、下、下、右｜右、下、下、右。", "缺口从下一段的第一格开始。"],
        instruction: "点击格子，在上、下、左、右之间切换。",
        options: ["上", "右", "下", "左"], solution: ["右", "下", "下"], slots: 3,
        rewardDigit: "6", rewardItem: "夜光疏散图", solvedText: "路线指向西侧楼梯，图角印着“梯＝6”。", wrongFeedback: "箭头没有延续前两段的四拍规律。",
        hints: ["竖线把相同的四步分开。", "缺口就是下一轮的前三步。", "右、下、下。"],
      },
      {
        id: "door-code", kind: "number", icon: "▦", symbol: "门", title: "消防门磁锁", position: point(1010, 745), requires: ["stair-map"],
        story: "门锁检修码由值班表推导，不是墙上被涂掉的旧密码。",
        prompt: "输入今晚的两位检修码。",
        evidence: ["规则：楼层数 × 当班人数。", "你在 12 楼，今晚仍在岗 3 人。"],
        instruction: "输入两位数。",
        options: [], solution: ["36"],
        rewardDigit: "3", rewardItem: "消防门磁卡", solvedText: "消防门弹开，门磁背面标着“门＝3”。", wrongFeedback: "按规则重新核对楼层数和当班人数。",
        hints: ["这是乘法，不是把两个数字并排。", "12 乘以 3。", "检修码是 36。"],
      },
    ],
    sideTasks: [
      { id: "water-coworker", icon: "杯", title: "伏案的同事", position: point(650, 330), prompt: "叫醒同事，并递给她一杯水。", completeText: "她保存文件，和你一起离开。" },
      { id: "turn-off-screen", icon: "屏", title: "亮着的会议室", position: point(985, 585), prompt: "关闭无人会议室的屏幕和插座。", completeText: "蓝光熄灭，窗外的月亮清楚了一点。" },
    ],
    hazards: [
      { id: "ceiling", title: "松动吊顶", rect: rect(540, 430, 140, 105), period: 8.5, warningFrom: 3, activeFrom: 6, warning: "吊顶灰尘簌簌落下", lesson: "火灾和漏水后应避开变形、掉粉的吊顶区域。", color: "#ffcf79" },
      { id: "smoke", title: "浓烟走廊", rect: rect(830, 650, 150, 90), period: 7.5, warningFrom: 2, activeFrom: 4.8, warning: "烟层正在降低", lesson: "烟雾中保持低姿，沿安全指示尽快离开，不要折返。", color: "#c8c5d3" },
    ],
    landmarks: [
      { title: "开放工位", icon: "桌", position: point(145, 200), size: 70 }, { title: "会议室", icon: "会", position: point(620, 250), size: 65 },
      { title: "电梯厅", icon: "梯", position: point(1050, 420), size: 70 }, { title: "安全出口", icon: "出", position: point(1465, 810), size: 88 },
    ],
    blockers: [rect(0, 0, 65, 900), rect(1535, 0, 65, 900), rect(500, 0, 45, 280), rect(810, 335, 45, 250), rect(1120, 590, 210, 50)],
  },
  {
    id: "flower-valley",
    day: 3,
    name: "春日花谷",
    subtitle: "不用走得最快",
    stamp: "生",
    environment: "flower-valley",
    intro: "把勿忘我的种子送到山顶小屋。花谷的旧水路、风铃和脚印都记得一部分答案。",
    goal: "修好花谷的四件小事，让山顶小屋想起今天。",
    ending: "你没有立刻赶路，而是在花里坐了一会儿。",
    code: "3142",
    finalSymbolOrder: ["轮", "席", "花", "印"],
    palette: palettes.flower,
    weatherIcon: "☀",
    startTime: "09:10",
    playerStart: point(120, 760),
    exit: point(1460, 125),
    route: [point(120, 760), point(350, 690), point(540, 735), point(720, 575), point(875, 470), point(1060, 520), point(1240, 300), point(1460, 125)],
    puzzles: [
      {
        id: "mill", kind: "sequence", icon: "◉", symbol: "轮", title: "沉默的小水磨", position: point(350, 690),
        story: "水轮没有坏，只是水槽被春叶塞住。木牌说，销钉不能在轮子受力时拔出。",
        prompt: "按正确顺序恢复水磨。",
        evidence: ["闸门开着，水槽堵塞，轮轴销钉歪斜。", "木牌：停水以后再碰轮轴。"],
        instruction: "选择四个动作。",
        options: ["关上引水闸", "清出水槽落叶", "扶正轮轴销钉", "重新开闸"], solution: ["关上引水闸", "清出水槽落叶", "扶正轮轴销钉", "重新开闸"],
        rewardDigit: "3", rewardItem: "水磨木销", solvedText: "水轮转动三圈，轮轴上亮起“轮＝3”。", wrongFeedback: "轮轴还在受力。先按木牌让水停下来。",
        hints: ["木牌首先要求“停水”。", "停水、清堵、修轴，最后才恢复水流。", "关闸 → 清叶 → 扶销 → 开闸。"],
      },
      {
        id: "picnic", kind: "choice", icon: "▨", symbol: "席", title: "少了一角的野餐席", position: point(710, 575), requires: ["mill"],
        story: "风把三块补丁吹到附近。只有一块的花纹和缺口两侧都能连续。",
        prompt: "选择正确的补丁。",
        evidence: ["缺口左边是蓝花，右边是黄格；上下针脚都是短—长—短。", "A：蓝花/黄格、短—长—短；B：黄格/蓝花；C：蓝花/黄格、长—短—长。"],
        instruction: "选出同时满足图案方向与针脚节奏的补丁。",
        options: ["A 蓝花补丁", "B 反向补丁", "C 长针脚补丁"], solution: ["A 蓝花补丁"],
        rewardDigit: "1", rewardItem: "蓝花布角", solvedText: "补丁严丝合缝，背面绣着“席＝1”。", wrongFeedback: "这块只满足了一个条件，再检查左右方向和针脚。",
        hints: ["两个条件必须同时成立。", "左右是蓝花到黄格，针脚是短—长—短。", "选择 A 蓝花补丁。"],
      },
      {
        id: "flower-bells", kind: "pattern", icon: "✿", symbol: "花", title: "风铃花圃", position: point(1060, 520), requires: ["picnic"],
        story: "四种风铃花按晨风顺序开合。石碑留下两个完整小节。",
        prompt: "补全第三小节。",
        evidence: ["蓝、白、蓝、黄｜蓝、白、蓝、黄。", "石碑：每次黄花合拢，就从蓝花重新开始。"],
        instruction: "补上第三小节的前三朵。",
        options: ["蓝", "白", "黄"], solution: ["蓝", "白", "蓝"], slots: 3,
        rewardDigit: "4", rewardItem: "风铃花籽", solvedText: "花圃同时摇响，花盆底刻着“花＝4”。", wrongFeedback: "黄花之后应该回到小节开头。",
        hints: ["竖线是每个小节的边界。", "第三小节重复前四朵的顺序。", "蓝、白、蓝。"],
      },
      {
        id: "footprints", kind: "number", icon: "❖", symbol: "印", title: "溪边脚印", position: point(1240, 300), requires: ["flower-bells"],
        story: "两只小动物都过了溪，但来回的脚印叠在一起。告示要求只数朝山顶的一组。",
        prompt: "有几组脚印朝向山顶？",
        evidence: ["兔印：两组朝山顶，一组朝河边。", "鹿印：没有朝山顶，三组朝河边。"],
        instruction: "输入朝山顶的总组数。",
        options: [], solution: ["2"],
        rewardDigit: "2", rewardItem: "溪石拓片", solvedText: "山顶方向恰有两组，石下藏着“印＝2”。", wrongFeedback: "题目只数“朝山顶”，不要把返程脚印也算进去。",
        hints: ["先分别看兔印和鹿印的方向。", "只有兔印有朝山顶的记录。", "答案是 2 组。"],
      },
    ],
    sideTasks: [
      { id: "tea", icon: "杯", title: "野餐的热茶", position: point(540, 735), prompt: "把掉在草边的杯子放回野餐篮。", completeText: "杯底留着一点春天的茶香。" },
      { id: "bee", icon: "蜂", title: "迷路的小蜂", position: point(885, 460), prompt: "把它引向开花更密的山坡。", completeText: "小蜂绕你一圈，钻进花海。" },
    ],
    hazards: [
      { id: "wind", title: "山谷强风", rect: rect(810, 335, 155, 105), period: 8, warningFrom: 2.5, activeFrom: 5.7, warning: "草尖齐齐伏向一边，风铃急响", lesson: "强风前会有一致的环境征兆；躲到岩石背风面再前进。", color: "#fff49b" },
      { id: "branch", title: "枯枝坠落", rect: rect(1175, 455, 120, 90), period: 9.5, warningFrom: 4, activeFrom: 7, warning: "树冠晃动，木屑落到小路", lesson: "听见树木断裂声或看见碎屑时，立即离开树冠下方。", color: "#ffd073" },
    ],
    landmarks: [
      { title: "花谷入口", icon: "花", position: point(115, 820), size: 62 }, { title: "旧水磨", icon: "轮", position: point(330, 630), size: 76 },
      { title: "彩木桥", icon: "桥", position: point(860, 610), size: 72 }, { title: "山顶小屋", icon: "⌂", position: point(1470, 78), size: 92 },
    ],
    blockers: [rect(0, 0, 60, 900), rect(1540, 0, 60, 900), rect(520, 430, 115, 90), rect(930, 175, 165, 80)],
  },
  {
    id: "rainbow-falls",
    day: 4,
    name: "彩虹瀑布",
    subtitle: "水会告诉你什么时候该等",
    stamp: "活",
    environment: "rainbow-falls",
    intro: "瀑布后的观景台只有在水位合适时开放。沿水声而上，恢复古老的水路标记。",
    goal: "读懂四种水流迹象，在彩虹出现前抵达观景台。",
    ending: "云没有立刻散。你和陌生旅人一起等到了彩虹。",
    code: "8206",
    finalSymbolOrder: ["阀", "叶", "舟", "虹"],
    palette: palettes.falls,
    weatherIcon: "◒",
    startTime: "15:26",
    playerStart: point(150, 160),
    exit: point(1435, 180),
    route: [point(150, 160), point(335, 300), point(250, 520), point(500, 700), point(760, 610), point(930, 400), point(1160, 520), point(1320, 330), point(1435, 180)],
    puzzles: [
      {
        id: "valves", kind: "pattern", icon: "◌", symbol: "阀", title: "三级分水阀", position: point(335, 300),
        story: "三道阀门要让水轮受力均匀。石槽上的水痕记录了昨天的状态。",
        prompt: "恢复三道阀门的开合状态。",
        evidence: ["左槽水痕高、中槽无水痕、右槽水痕高。", "刻字：有水痕为开，无水痕为关。"],
        instruction: "点击三格，在“开/关”之间切换。",
        options: ["开", "关"], solution: ["开", "关", "开"], slots: 3,
        rewardDigit: "8", rewardItem: "青铜阀柄", solvedText: "水轮平稳转动，阀柄上浮出“阀＝8”。", wrongFeedback: "阀门状态和三条石槽的水痕没有对应。",
        hints: ["逐格对照左、中、右水槽。", "高水痕代表开，无水痕代表关。", "开、关、开。"],
      },
      {
        id: "lily-path", kind: "sequence", icon: "❀", symbol: "叶", title: "睡莲踏石", position: point(500, 700), requires: ["valves"],
        story: "四片大叶会在被踩后下沉。蜻蜓停留的次序提示了安全路线。",
        prompt: "按蜻蜓到访顺序踏过睡莲。",
        evidence: ["蓝蜻蜓停在圆叶，红蜻蜓停在缺口叶，金蜻蜓停在尖叶，最后都飞向双瓣叶。", "岸边画着：蓝 → 红 → 金 → 相会。"],
        instruction: "依次选择叶片。",
        options: ["圆叶", "缺口叶", "尖叶", "双瓣叶"], solution: ["圆叶", "缺口叶", "尖叶", "双瓣叶"],
        rewardDigit: "2", rewardItem: "睡莲露珠", solvedText: "最后一片叶托起石牌：“叶＝2”。", wrongFeedback: "叶片正在下沉。回想三只蜻蜓的颜色顺序。",
        hints: ["岸边的颜色顺序对应蜻蜓停过的叶形。", "蓝是圆叶，红是缺口叶，金是尖叶。", "圆叶 → 缺口叶 → 尖叶 → 双瓣叶。"],
      },
      {
        id: "gondola", kind: "choice", icon: "舟", symbol: "舟", title: "峡谷吊篮", position: point(930, 400), requires: ["lily-path"],
        story: "吊篮限重 90 公斤。你、背包和三块配重必须做出唯一安全取舍。",
        prompt: "选择不会超重又能压稳缆绳的组合。",
        evidence: ["你 55kg，背包 10kg；吊篮至少需要 15kg 配重。", "蓝石 10kg，黄石 15kg，红石 25kg；总重不得超过 90kg。"],
        instruction: "选择一块配重。",
        options: ["蓝石 10kg", "黄石 15kg", "红石 25kg"], solution: ["黄石 15kg"],
        rewardDigit: "0", rewardItem: "吊篮黄配重", solvedText: "吊篮恰好稳定，配重底面刻着“舟＝0”。", wrongFeedback: "这个选择没有同时满足最低配重和总限重。",
        hints: ["先算你和背包已经有 65kg。", "配重至少 15kg，但加完不能超过 90kg。", "黄石 15kg 是唯一稳妥选择。"],
      },
      {
        id: "rainbow-time", kind: "number", icon: "⌒", symbol: "虹", title: "观景台日晷", position: point(1320, 330), requires: ["gondola"],
        story: "石刻写着彩虹会在阳光越过第六道水帘时出现。计时轮每道间隔三分钟。",
        prompt: "从第一道到第六道需要等待几分钟？",
        evidence: ["相邻水帘之间间隔 3 分钟。", "从第一道数到第六道，共跨过 5 个间隔。"],
        instruction: "输入等待分钟数。",
        options: [], solution: ["15"],
        rewardDigit: "6", rewardItem: "彩虹观景牌", solvedText: "日晷指针落定，背面显出“虹＝6”。", wrongFeedback: "不要把水帘数量当成间隔数量。",
        hints: ["六道水帘之间只有五个间隔。", "5 个间隔，每个 3 分钟。", "答案是 15 分钟。"],
      },
    ],
    sideTasks: [
      { id: "photo", icon: "相", title: "起雾的镜头", position: point(760, 610), prompt: "替旅人擦干相机镜头。", completeText: "她答应把彩虹照片寄给你。" },
      { id: "fern", icon: "蕨", title: "洞里的幼蕨", position: point(1160, 520), prompt: "把挡住滴水的碎石移开。", completeText: "水珠重新落在卷曲的新叶上。" },
    ],
    hazards: [
      { id: "rapid", title: "突涨急流", rect: rect(570, 510, 150, 115), period: 8.5, warningFrom: 2.5, activeFrom: 5.5, warning: "上游水声突然变沉，泡沫加速", lesson: "溪流变浑、变响或泡沫加速时，立即离开低处。", color: "#91efff" },
      { id: "wet-rock", title: "落石水帘", rect: rect(1190, 260, 125, 100), period: 9, warningFrom: 3.5, activeFrom: 6.4, warning: "岩缝渗水，细石开始弹落", lesson: "瀑布和崖壁下方出现细石时，不要停留拍照。", color: "#ffe394" },
    ],
    landmarks: [
      { title: "水车入口", icon: "轮", position: point(150, 95), size: 72 }, { title: "莲叶池", icon: "叶", position: point(480, 770), size: 70 },
      { title: "大瀑布", icon: "瀑", position: point(1100, 170), size: 100 }, { title: "彩虹台", icon: "虹", position: point(1450, 115), size: 92 },
    ],
    blockers: [rect(0, 0, 60, 900), rect(1540, 0, 60, 900), rect(580, 190, 130, 170), rect(1030, 600, 175, 100)],
  },
  {
    id: "autumn-river",
    day: 5,
    name: "秋日河湾",
    subtitle: "回家的路也值得认真选择",
    stamp: "明",
    environment: "autumn-river",
    intro: "傍晚的渡口即将停航。替村里送回四样东西，再赶上水位上涨前的最后一班船。",
    goal: "完成河湾交接，辨认潮汐和渡船留下的四个标记。",
    ending: "渡船靠岸时，茶馆的人问你：要不要一起吃晚饭？",
    code: "2418",
    finalSymbolOrder: ["潮", "秤", "灯", "票"],
    palette: palettes.autumn,
    weatherIcon: "◔",
    startTime: "17:06",
    playerStart: point(130, 180),
    exit: point(1460, 720),
    route: [point(130, 180), point(360, 240), point(540, 410), point(720, 300), point(860, 525), point(1080, 435), point(1240, 620), point(1460, 720)],
    puzzles: [
      {
        id: "tide-route", kind: "sequence", icon: "≈", symbol: "潮", title: "潮汐路标", position: point(360, 240),
        story: "浅滩快被淹没。旧路标按地势从低到高标出撤离顺序。",
        prompt: "把四处地标按安全撤离方向排列。",
        evidence: ["沙洲海拔 1m，芦苇岸 2m，果园坡 4m，石桥台 6m。", "水位上涨时应持续往更高处移动。"],
        instruction: "从最低处开始依次选择。",
        options: ["沙洲", "芦苇岸", "果园坡", "石桥台"], solution: ["沙洲", "芦苇岸", "果园坡", "石桥台"],
        rewardDigit: "2", rewardItem: "潮汐木尺", solvedText: "木尺底端露出“潮＝2”。", wrongFeedback: "路线中出现了向低处折返。",
        hints: ["把四个海拔数字排成升序。", "从 1 米一路走向 6 米。", "沙洲 → 芦苇岸 → 果园坡 → 石桥台。"],
      },
      {
        id: "ferry-balance", kind: "choice", icon: "⚖", symbol: "秤", title: "渡船配载秤", position: point(720, 300), requires: ["tide-route"],
        story: "船头已有 30kg，船尾已有 20kg。必须再放一筐货，让两端相差不超过 5kg。",
        prompt: "选择放到船尾的货筐。",
        evidence: ["船头 30kg，船尾 20kg。", "梨筐 5kg，茶筐 10kg，木料 20kg。"],
        instruction: "选择一筐放到船尾。",
        options: ["梨筐 5kg", "茶筐 10kg", "木料 20kg"], solution: ["茶筐 10kg"],
        rewardDigit: "4", rewardItem: "渡船铜砝码", solvedText: "两端恰好平衡，秤盘刻着“秤＝4”。", wrongFeedback: "放上以后，两端重量差仍然超过 5kg。",
        hints: ["船尾需要接近船头的 30kg。", "20kg 再加多少会等于 30kg？", "选择茶筐 10kg。"],
      },
      {
        id: "orchard-lights", kind: "pattern", icon: "✦", symbol: "灯", title: "果园归途灯", position: point(1080, 435), requires: ["ferry-balance"],
        story: "果园灯按两亮一暗循环，缺失的三盏决定夜路方向。",
        prompt: "补全灯光状态。",
        evidence: ["亮、亮、暗｜亮、亮、暗。", "每组三盏后重新开始。"],
        instruction: "点击三个格子切换亮/暗。",
        options: ["亮", "暗"], solution: ["亮", "亮", "暗"], slots: 3,
        rewardDigit: "1", rewardItem: "琥珀小灯", solvedText: "灯串向码头延伸，灯帽内写着“灯＝1”。", wrongFeedback: "没有延续“两亮一暗”的完整小节。",
        hints: ["每组三盏完全一样。", "新一组仍从两盏亮灯开始。", "亮、亮、暗。"],
      },
      {
        id: "last-ticket", kind: "number", icon: "券", symbol: "票", title: "最后一张船票", position: point(1240, 620), requires: ["orchard-lights"],
        story: "票箱按乘客数发号。今天前四班分别带走 3、5、4、6 人，你是下一位。",
        prompt: "你的顺序号是多少？",
        evidence: ["前四班总人数：3 + 5 + 4 + 6。", "你的号码比此前总人数多 1。"],
        instruction: "输入两位顺序号。",
        options: [], solution: ["19"],
        rewardDigit: "8", rewardItem: "末班船票", solvedText: "第 19 号船票背面印着“票＝8”。", wrongFeedback: "先求前四班总人数，再把自己算进去。",
        hints: ["3+5+4+6 等于 18。", "你是此前 18 人之后的一位。", "答案是 19。"],
      },
    ],
    sideTasks: [
      { id: "tea-jar", icon: "茶", title: "茶馆的空罐", position: point(540, 410), prompt: "把漂到岸边的茶罐捡回来。", completeText: "老板擦干茶罐，给你留了一张晚饭座位。" },
      { id: "scarf", icon: "巾", title: "芦苇上的围巾", position: point(860, 525), prompt: "把围巾交给等船的孩子。", completeText: "孩子围好围巾，向你挥了挥手。" },
    ],
    hazards: [
      { id: "mud", title: "吞脚软泥", rect: rect(560, 520, 145, 100), period: 8, warningFrom: 2.7, activeFrom: 5.7, warning: "泥面鼓泡，落叶慢慢下陷", lesson: "河滩泥面鼓泡或物体下陷时，不要试探，沿坚实岸线绕行。", color: "#e4b060" },
      { id: "rising-water", title: "上涨河水", rect: rect(1150, 650, 145, 100), period: 9, warningFrom: 3.3, activeFrom: 6.2, warning: "水线越过岸边第二块白石", lesson: "水位上涨时及时离开沙洲，不要为捡东西返回。", color: "#7de4e2" },
    ],
    landmarks: [
      { title: "老茶馆", icon: "茶", position: point(125, 105), size: 78 }, { title: "芦苇湾", icon: "苇", position: point(520, 510), size: 70 },
      { title: "柿子园", icon: "果", position: point(1010, 305), size: 82 }, { title: "末班渡口", icon: "舟", position: point(1470, 780), size: 90 },
    ],
    blockers: [rect(0, 0, 60, 900), rect(1540, 0, 60, 900), rect(430, 610, 160, 105), rect(890, 125, 165, 95)],
  },
  {
    id: "mountain-storm",
    day: 6,
    name: "山谷骤雨",
    subtitle: "真正的勇敢是及时改变计划",
    stamp: "天",
    environment: "storm-mountain",
    intro: "徒步途中雷雨突然逼近。原定路线已不再安全，你要帮助同行者找到高处避难亭。",
    goal: "观察山势、雷声与水流，重建一条会随天气改变的安全路线。",
    ending: "避难亭里，大家把剩下的热水分成了五杯。",
    code: "6318",
    finalSymbolOrder: ["坡", "雷", "哨", "亭"],
    palette: palettes.storm,
    weatherIcon: "ϟ",
    startTime: "14:37",
    playerStart: point(120, 790),
    exit: point(1430, 105),
    route: [point(120, 790), point(330, 720), point(440, 520), point(690, 600), point(780, 370), point(1040, 440), point(1190, 245), point(1430, 105)],
    puzzles: [
      {
        id: "high-route", kind: "choice", icon: "△", symbol: "坡", title: "被冲掉的岔路牌", position: point(330, 720),
        story: "三条路分别经过河床、孤立山脊和缓坡树林。天气广播已经给出排除条件。",
        prompt: "选择雷雨中相对安全的上行路线。",
        evidence: ["广播：远离河床，也不要站上暴露山脊。", "A 沿河床；B 上孤脊；C 走有矮林的缓坡。"],
        instruction: "选择路线。",
        options: ["A 河床近路", "B 孤脊视野路", "C 矮林缓坡"], solution: ["C 矮林缓坡"],
        rewardDigit: "6", rewardItem: "防水路线牌", solvedText: "路牌翻面后写着“坡＝6”。", wrongFeedback: "这条路正好经过广播要求避开的地形。",
        hints: ["河床和孤立高点都被点名排除。", "剩下有矮林但不靠大树的缓坡。", "选择 C 矮林缓坡。"],
      },
      {
        id: "lightning", kind: "sequence", icon: "ϟ", symbol: "雷", title: "雷雨应对牌", position: point(440, 520), requires: ["high-route"],
        story: "同行者想躲到最高的树下。旧应对牌缺了编号，需要按安全动作重新排序。",
        prompt: "安排雷雨避险步骤。",
        evidence: ["先离开水边和制高点；再取下金属长杆；分散蹲低；最后等待雷声远去。", "牌脚注明：不要聚成一团。"],
        instruction: "依次选择四个动作。",
        options: ["离开水边和山脊", "放下金属登山杖", "分散并降低身体", "等待雷声远去"], solution: ["离开水边和山脊", "放下金属登山杖", "分散并降低身体", "等待雷声远去"],
        rewardDigit: "3", rewardItem: "绝缘杖套", solvedText: "牌面恢复完整，角落标着“雷＝3”。", wrongFeedback: "在危险地形上整理装备会耽误撤离。先离开暴露位置。",
        hints: ["第一步应先改变所在位置。", "撤离危险地形后处理金属物，再分散降低身体。", "离开 → 放杖 → 分散蹲低 → 等待。"],
      },
      {
        id: "echo-whistle", kind: "pattern", icon: "♪", symbol: "哨", title: "救援回声哨", position: point(780, 370), requires: ["lightning"],
        story: "雾里只能靠回声辨路。救援哨按短短长的三拍循环。",
        prompt: "补全下一组求救信号。",
        evidence: ["短、短、长｜短、短、长。", "石壁回声在每组三拍后停一拍。"],
        instruction: "点击三格切换短/长。",
        options: ["短", "长"], solution: ["短", "短", "长"], slots: 3,
        rewardDigit: "1", rewardItem: "橙色救援哨", solvedText: "远处传来回应，哨身刻着“哨＝1”。", wrongFeedback: "节奏没有形成完整的三拍求救小节。",
        hints: ["竖线分开了重复的小节。", "每一组都是两短一长。", "短、短、长。"],
      },
      {
        id: "shelter-lock", kind: "number", icon: "⌂", symbol: "亭", title: "避难亭物资锁", position: point(1190, 245), requires: ["echo-whistle"],
        story: "物资锁密码是营地编号与救援队数的乘积。",
        prompt: "计算两位物资锁密码。",
        evidence: ["你在 6 号营地。", "今天有 3 支救援队巡山。"],
        instruction: "输入乘积。",
        options: [], solution: ["18"],
        rewardDigit: "8", rewardItem: "避难亭物资包", solvedText: "锁扣打开，急救毯标签上写着“亭＝8”。", wrongFeedback: "规则要求相乘，不是把两个编号连接起来。",
        hints: ["用营地编号乘救援队数。", "6 × 3。", "密码是 18。"],
      },
    ],
    sideTasks: [
      { id: "raincoat", icon: "衣", title: "破开的雨衣", position: point(690, 600), prompt: "用胶带替同行者补好雨衣。", completeText: "他把自己的备用灯交给了你。" },
      { id: "thermos", icon: "壶", title: "滚下坡的水壶", position: point(1040, 440), prompt: "在下一阵雨前捡回保温壶。", completeText: "壶里的水还温着。" },
    ],
    hazards: [
      { id: "debris", title: "碎石滑落", rect: rect(575, 410, 145, 110), period: 8, warningFrom: 2.7, activeFrom: 5.5, warning: "坡上响起连续的石子滚动声", lesson: "先有小石滚落时就是离开坡脚的信号，不要停下观察。", color: "#ffd36a" },
      { id: "flash-flood", title: "山洪沟", rect: rect(990, 245, 150, 105), period: 9, warningFrom: 3, activeFrom: 6, warning: "沟里水声突然放大，枯枝快速漂来", lesson: "山沟水声骤响、漂浮物增多时，立刻向两侧高处撤离。", color: "#82dff2" },
    ],
    landmarks: [
      { title: "低地营位", icon: "帐", position: point(115, 845), size: 72 }, { title: "木索桥", icon: "桥", position: point(600, 650), size: 74 },
      { title: "茶歇亭", icon: "茶", position: point(1020, 520), size: 72 }, { title: "高处避难亭", icon: "亭", position: point(1440, 55), size: 96 },
    ],
    blockers: [rect(0, 0, 60, 900), rect(1540, 0, 60, 900), rect(365, 265, 155, 105), rect(830, 535, 145, 95)],
  },
  {
    id: "snow-last-train",
    day: 7,
    name: "暴雪末班车",
    subtitle: "让彼此都赶得上温暖",
    stamp: "再",
    environment: "snow-station",
    intro: "暴雪让小站停电。末班车是否进站，要靠你恢复信号、找到候车的人并确认安全站台。",
    goal: "修复雪夜小站的四个系统，帮助所有人登上末班车。",
    ending: "你把最后一个暖手包塞给孩子。列车在雪里慢慢亮起。",
    code: "5402",
    finalSymbolOrder: ["号", "灯", "牌", "厢"],
    palette: palettes.snow,
    weatherIcon: "❄",
    startTime: "21:15",
    playerStart: point(110, 470),
    exit: point(1490, 470),
    route: [point(110, 470), point(330, 360), point(540, 480), point(760, 330), point(930, 480), point(1150, 350), point(1320, 480), point(1490, 470)],
    puzzles: [
      {
        id: "signal-order", kind: "sequence", icon: "●", symbol: "号", title: "积雪信号机", position: point(330, 360),
        story: "信号机被雪覆盖。检修卡要求在通电前完成机械检查。",
        prompt: "按检修顺序恢复信号。",
        evidence: ["检修卡：清雪 → 查灯罩 → 扳手动杆 → 恢复电源。", "红字：带电时禁止触碰结冰灯罩。"],
        instruction: "依次选择四个动作。",
        options: ["清除积雪", "检查灯罩裂纹", "扳动手动杆", "恢复信号电源"], solution: ["清除积雪", "检查灯罩裂纹", "扳动手动杆", "恢复信号电源"],
        rewardDigit: "5", rewardItem: "信号机手柄", solvedText: "绿灯穿过雪幕，底座亮出“号＝5”。", wrongFeedback: "机械检查还没完成，不能先通电。",
        hints: ["卡片上的箭头就是操作顺序。", "先清理和检查，再操作，最后通电。", "清雪 → 查灯罩 → 扳杆 → 通电。"],
      },
      {
        id: "lamp-pattern", kind: "pattern", icon: "✦", symbol: "灯", title: "候车室应急灯", position: point(760, 330), requires: ["signal-order"],
        story: "应急灯用暖、冷、冷三色循环指向有供暖的房间。",
        prompt: "补全下一组三盏灯。",
        evidence: ["暖、冷、冷｜暖、冷、冷。", "每组三盏后方向箭头重新出现。"],
        instruction: "点击三格切换暖/冷。",
        options: ["暖", "冷"], solution: ["暖", "冷", "冷"], slots: 3,
        rewardDigit: "4", rewardItem: "应急灯电池", solvedText: "暖色箭头指向候车室，灯座写着“灯＝4”。", wrongFeedback: "颜色没有延续三盏一组的循环。",
        hints: ["观察竖线两侧是否相同。", "下一组仍以暖灯开始，随后两盏冷灯。", "暖、冷、冷。"],
      },
      {
        id: "lost-tag", kind: "choice", icon: "牌", symbol: "牌", title: "无人认领的行李牌", position: point(1150, 350), requires: ["lamp-pattern"],
        story: "三位乘客在找箱子，行李牌只留下目的地和颜色线索。",
        prompt: "把蓝箱交给正确的人。",
        evidence: ["蓝箱去北山；红箱不去海湾；陈姨去海湾。", "阿洛不去北山；小岚的箱子是蓝色。"],
        instruction: "选择蓝箱主人。",
        options: ["陈姨", "阿洛", "小岚"], solution: ["小岚"],
        rewardDigit: "0", rewardItem: "北山行李牌", solvedText: "小岚道谢，行李牌夹层写着“牌＝0”。", wrongFeedback: "这位乘客的目的地或颜色与已知条件冲突。",
        hints: ["最后一句已经直接限定了蓝箱的主人。", "小岚的箱子是蓝色。", "选择小岚。"],
      },
      {
        id: "carriage", kind: "number", icon: "▤", symbol: "厢", title: "被雪盖住的编组表", position: point(1320, 480), requires: ["lost-tag"],
        story: "暖气车厢编号是列车总节数减去两节货厢。",
        prompt: "暖气车厢编号是多少？",
        evidence: ["末班车共 8 节，从车头编号 1—8。", "最后两节是货厢；暖气车厢紧挨货厢之前。"],
        instruction: "输入一位车厢编号。",
        options: [], solution: ["6"],
        rewardDigit: "2", rewardItem: "暖气车厢票", solvedText: "第 6 车厢亮灯，编组表背面印着“厢＝2”。", wrongFeedback: "先定位最后两节货厢，再找它们前面紧挨的一节。",
        hints: ["8 节车厢中，7 和 8 是货厢。", "货厢前一节就是 6。", "答案是 6 号车厢。"],
      },
    ],
    sideTasks: [
      { id: "warm-pack", icon: "暖", title: "冻僵的候车人", position: point(540, 480), prompt: "把备用暖手包交给老人。", completeText: "老人把围巾分给了旁边的孩子。" },
      { id: "snowman", icon: "雪", title: "站台小雪人", position: point(930, 480), prompt: "把掉落的红帽放回雪人头上。", completeText: "候车室里传来一小片笑声。" },
    ],
    hazards: [
      { id: "icicle", title: "屋檐冰锥", rect: rect(450, 265, 130, 100), period: 8, warningFrom: 3, activeFrom: 5.8, warning: "冰锥出现裂纹，细雪簌簌落下", lesson: "升温或震动时远离屋檐冰锥下方。", color: "#c8f5ff" },
      { id: "train", title: "无灯调车", rect: rect(1010, 530, 170, 90), period: 9.2, warningFrom: 3.5, activeFrom: 6.5, warning: "铁轨轻震，远处传来低沉鸣笛", lesson: "任何时候都不要在轨道上停留；听到震动或鸣笛立即离开。", color: "#ffbd70" },
    ],
    landmarks: [
      { title: "站前咖啡", icon: "杯", position: point(105, 350), size: 72 }, { title: "候车室", icon: "候", position: point(680, 210), size: 88 },
      { title: "信号桥", icon: "号", position: point(1060, 250), size: 75 }, { title: "末班列车", icon: "车", position: point(1490, 570), size: 105 },
    ],
    blockers: [rect(0, 0, 60, 900), rect(1540, 0, 60, 900), rect(400, 600, 220, 55), rect(820, 175, 160, 70)],
  },
  {
    id: "glowing-river",
    day: 8,
    name: "发光地下河",
    subtitle: "把记住的日子带回清晨",
    stamp: "见",
    environment: "glow-cave",
    intro: "最后的洞穴没有路牌。八天里学会的观察、等待与互助，会在发光地下河边再次被用到。",
    goal: "穿过会呼吸的洞穴，找回最后四枚记忆符号。",
    ending: "出口外没有奇迹，只有普通的清晨。八枚印章排成：好好生活，明天再见。",
    code: "5073",
    finalSymbolOrder: ["晶", "波", "桥", "晨"],
    palette: palettes.cave,
    weatherIcon: "✧",
    startTime: "05:07",
    playerStart: point(120, 740),
    exit: point(1470, 120),
    route: [point(120, 740), point(350, 620), point(520, 760), point(700, 520), point(900, 640), point(1050, 390), point(1260, 420), point(1470, 120)],
    puzzles: [
      {
        id: "crystal-safe", kind: "choice", icon: "◇", symbol: "晶", title: "共鸣水晶门", position: point(350, 620),
        story: "三簇水晶发出不同征兆。你必须用过去学会的危险判断选择可以靠近的一簇。",
        prompt: "选择没有显示失稳征兆的水晶。",
        evidence: ["A 有裂纹且落粉；B 光稳定、周围无碎屑；C 间歇尖响并轻微晃动。", "危险常先以裂纹、碎屑、异常声音和晃动出现。"],
        instruction: "选择可安全检查的一簇。",
        options: ["A 裂纹水晶", "B 稳定水晶", "C 尖响水晶"], solution: ["B 稳定水晶"],
        rewardDigit: "5", rewardItem: "稳定晶片", solvedText: "水晶门安静开启，晶片折射出“晶＝5”。", wrongFeedback: "这簇已经发出明显的结构失稳信号。",
        hints: ["回想坠物发生前会出现什么。", "排除有裂纹、落粉、尖响或晃动的目标。", "选择 B 稳定水晶。"],
      },
      {
        id: "river-pulse", kind: "pattern", icon: "≈", symbol: "波", title: "会呼吸的地下河", position: point(700, 520), requires: ["crystal-safe"],
        story: "河面按低、低、高、静止的四拍呼吸。安全踏石只在下一拍出现。",
        prompt: "补全下一轮前三拍。",
        evidence: ["低、低、高、静｜低、低、高、静。", "每次静止后，波纹从低处重新开始。"],
        instruction: "点击三格切换低/高/静。",
        options: ["低", "高", "静"], solution: ["低", "低", "高"], slots: 3,
        rewardDigit: "0", rewardItem: "河光水滴", solvedText: "踏石浮出水面，水滴里亮着“波＝0”。", wrongFeedback: "节拍没有从静止后的第一拍重新开始。",
        hints: ["静止是每轮的终点。", "静止之后重复低、低、高。", "低、低、高。"],
      },
      {
        id: "flower-bridge", kind: "sequence", icon: "✿", symbol: "桥", title: "发光花桥", position: point(1050, 390), requires: ["river-pulse"],
        story: "四朵石花分别记着前四天的动作。只有按“先安全、再前进、最后等待”的逻辑触碰才会成桥。",
        prompt: "排列四个曾救过你的动作。",
        evidence: ["先切断危险来源；再提醒同行者；确认路线后前进；抵达安全处等待。", "石花刻着：断、告、行、等。"],
        instruction: "按处置先后选择。",
        options: ["断", "告", "行", "等"], solution: ["断", "告", "行", "等"],
        rewardDigit: "7", rewardItem: "发光花瓣", solvedText: "花瓣连成桥，桥心写着“桥＝7”。", wrongFeedback: "行动太早或提醒太晚都会让别人留在危险里。",
        hints: ["首先控制危险来源。", "安全后要提醒他人，确认路线再走，最后等待。", "断 → 告 → 行 → 等。"],
      },
      {
        id: "morning-count", kind: "number", icon: "☼", symbol: "晨", title: "通向清晨的石门", position: point(1260, 420), requires: ["flower-bridge"],
        story: "石门问的不是死亡次数，而是一路上已经认真度过了多少个清晨。",
        prompt: "这是旅程的第几个清晨？",
        evidence: ["日志从 DAY 01 排到 DAY 08。", "眼前的洞穴标题写着 DAY 08。"],
        instruction: "输入一位数字。",
        options: [], solution: ["8"],
        rewardDigit: "3", rewardItem: "清晨石印", solvedText: "第八道晨光落下，石印上显出“晨＝3”。", wrongFeedback: "不要数失败次数，看看日志封面的 DAY 编号。",
        hints: ["答案就在当前关卡编号。", "这是 DAY 08。", "输入 8。"],
      },
    ],
    sideTasks: [
      { id: "bat", icon: "翼", title: "落单的小蝠", position: point(520, 760), prompt: "熄灭强光，让它沿微光飞回洞顶。", completeText: "黑暗不再显得空，翅膀声渐渐远去。" },
      { id: "old-cart", icon: "车", title: "停住的旧矿车", position: point(900, 640), prompt: "把挡轮石重新垫稳。", completeText: "矿车不再晃动，里面躺着八朵干花。" },
    ],
    hazards: [
      { id: "steam", title: "间歇蒸汽", rect: rect(570, 390, 145, 110), period: 8, warningFrom: 2.8, activeFrom: 5.6, warning: "岩缝先冒出细白雾，水珠开始震动", lesson: "间歇喷口会先泄出细雾；看见预兆应等待喷发结束。", color: "#bfffee" },
      { id: "crystal-fall", title: "水晶崩落", rect: rect(1120, 270, 135, 100), period: 9.5, warningFrom: 3.7, activeFrom: 6.8, warning: "洞顶晶尘落下，传来清脆裂声", lesson: "洞顶出现落尘和裂声时，不要停在正下方。", color: "#a88cff" },
    ],
    landmarks: [
      { title: "晶簇入口", icon: "晶", position: point(115, 805), size: 78 }, { title: "地下河", icon: "波", position: point(690, 660), size: 84 },
      { title: "花桥", icon: "桥", position: point(1030, 300), size: 82 }, { title: "日出裂隙", icon: "晨", position: point(1480, 65), size: 100 },
    ],
    blockers: [rect(0, 0, 60, 900), rect(1540, 0, 60, 900), rect(390, 330, 145, 110), rect(820, 245, 170, 95)],
  },
];

export const CAMPAIGN_PHRASE = "好好生活，明天再见";

function validateCampaign() {
  const levelIds = new Set<string>();
  for (const level of LEVELS) {
    if (levelIds.has(level.id)) throw new Error(`Duplicate level id: ${level.id}`);
    levelIds.add(level.id);
    if (level.puzzles.length !== 4) throw new Error(`${level.name} must contain exactly four main puzzles`);
    if (level.sideTasks.length !== 2 || level.hazards.length !== 2) throw new Error(`${level.name} content budget is incomplete`);
    const symbols = new Map(level.puzzles.map((puzzle) => [puzzle.symbol, puzzle.rewardDigit]));
    const derivedCode = level.finalSymbolOrder.map((symbol) => symbols.get(symbol) ?? "?").join("");
    if (derivedCode !== level.code) throw new Error(`${level.name} final symbol order does not derive ${level.code}`);
    for (const puzzle of level.puzzles) {
      if (puzzle.hints.length !== 3) throw new Error(`${puzzle.title} must include H1-H3 hints`);
      if (puzzle.kind === "pattern" && puzzle.solution.length !== puzzle.slots) throw new Error(`${puzzle.title} pattern slots mismatch`);
      for (const required of puzzle.requires ?? []) {
        if (!level.puzzles.some((candidate) => candidate.id === required)) throw new Error(`${puzzle.title} requires an unknown puzzle`);
      }
    }
  }
  if (LEVELS.map((level) => level.stamp).join("") !== CAMPAIGN_PHRASE.replace("，", "")) throw new Error("Campaign stamps do not form the final phrase");
}

validateCampaign();

export function getLevel(index: number) {
  return LEVELS[Math.max(0, Math.min(LEVELS.length - 1, index))];
}
