export * from "./worldSchema";
import type { WorldDesign } from "./worldSchema";
import day1 from "./worlds/day01";
import day2 from "./worlds/day02";
import day3 from "./worlds/day03";
import day4 from "./worlds/day04";
import day5 from "./worlds/day05";
import day6 from "./worlds/day06";
import day7 from "./worlds/day07";
import day8 from "./worlds/day08";
export const WORLDS: WorldDesign[] = [day1, day2, day3, day4, day5, day6, day7, day8];
