import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { loadSource } from '../../../tests/load-source.mjs';
const {default:pack}=loadSource('src/campaign/exploration/day05.ts');
const {default:outside}=loadSource('src/campaign/worlds/day05.ts');
const {buildWorldNavigation}=loadSource('src/campaign/worldGeometry.ts');
const {allDiscoveries,settleDiscovery,earnedAchievements}=loadSource('src/campaign/exploration/discoveries.ts');
const nodes=allDiscoveries(pack), nav=buildWorldNavigation(pack.room.world,new Set()), main=buildWorldNavigation(outside,new Set());
const results=[];
function check(name,fn){try{fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.message});}}
function route(n,a,b){assert.ok(n.isWalkable(a),'start is not walkable');assert.ok(n.isWalkable(b),'end is not walkable');const points=n.route(a,b,()=>false,0);assert.ok(points.length,'empty route');let last=a;for(const p of points){assert.ok(n.visible(last,p),'segment crosses collision');last=p;}assert.ok(Math.hypot(last.x-b.x,last.y-b.y)<1,'route snapped away from stance');}
check('content and dependency graph',()=>{const ids=new Set(nodes.map(n=>n.id));assert.equal(ids.size,nodes.length);assert.equal(pack.outside.length,3);assert.equal(pack.room.nodes.length,10);assert.equal(nodes.filter(n=>n.reward).length,5);assert.equal(pack.achievements.length,2);const visiting=new Set(),done=new Set();function visit(id){assert.ok(ids.has(id),id);assert.ok(!visiting.has(id),'cycle');if(done.has(id))return;visiting.add(id);const n=nodes.find(n=>n.id===id);for(const dep of [...n.requires??[],...n.sequence??[]])visit(dep);visiting.delete(id);done.add(id);}nodes.forEach(n=>{visit(n.id);assert.ok(n.id.startsWith('d05-'));assert.ok(n.visual.support);assert.ok(n.baked||n.art||n.animal);for(const s of n.sequence??[])assert.ok(pack.room.nodes.some(n=>n.id===s&&n.kind==='inspect'));});for(const a of pack.achievements)for(const id of a.requires)assert.ok(ids.has(id));});
check('outdoor doorway reachable without main flags',()=>route(main,outside.spawn,pack.room.entry.approach));
for(const n of pack.outside)check(n.id+' outdoor stance',()=>route(main,outside.spawn,n.approach));
for(const n of [...pack.room.nodes,{id:'return',approach:pack.room.world.approaches.exit}])check(n.id+' room round trip',()=>{route(nav,pack.room.world.spawn,n.approach);route(nav,n.approach,pack.room.world.approaches.exit);});
const scale=(x,y)=>({x:x*1600/1672,y:y*900/941});
for(const [name,x,y] of [['stove',210,410],['sink',325,383],['jar shelf',530,310],['bar',670,490],['pillar',880,250],['desk',1100,360],['chair',1160,409],['east shelf',1520,410],['tea table',1300,585],['west cushion',1170,590],['east cushion',1450,590],['west door wall',160,640],['east door post',380,685],['back wall',1000,300],['front wall',900,799]])check('blocked '+name,()=>assert.equal(nav.isWalkable(scale(x,y)),false));
for(const n of nodes.filter(n=>n.animal))check(n.id+' patrol loop',()=>{const active=pack.outside.includes(n)?main:nav;const p=[n.position,...n.patrol,n.patrol[0]];for(let i=1;i<p.length;i++)route(active,p[i-1],p[i]);});
check('PNG sources, baked polygons and asset bounds',()=>{for(const file of ['public'+pack.room.background,'design/exploration-014/day05/river-teahouse-source.png']){const b=readFileSync(file);assert.equal(b.subarray(0,8).toString('hex'),'89504e470d0a1a0a');assert.equal(b.readUInt32BE(16),1672);assert.equal(b.readUInt32BE(20),941);}for(const n of nodes){for(const p of n.baked??[])assert.ok(p.x>=0&&p.x<=1600&&p.y>=0&&p.y<=900);for(const art of [n.art,n.afterArt].filter(Boolean)){const b=readFileSync('public'+art.src);assert.ok(art.width>0&&art.height>0);if(art.crop)assert.ok(art.crop.x>=0&&art.crop.y>=0&&art.crop.x+art.crop.width<=b.readUInt32BE(16)&&art.crop.y+art.crop.height<=b.readUInt32BE(20));}}});
check('actual chain rejects missing recipe and wrong order; rewards are idempotent',()=>{const flags=new Set(),history=[],get=id=>nodes.find(n=>n.id===id),act=id=>settleDiscovery(get(id),nodes,flags,history);assert.equal(act('d05-preserve').status,'locked');assert.equal(act('d05-jam-card').status,'locked');act('d05-recipe');act('d05-simmer');act('d05-wash');act('d05-fruit');assert.equal(act('d05-preserve').status,'sequence');assert.equal(flags.has('d05-preserve'),false);for(const id of get('d05-preserve').sequence)act(id);assert.equal(act('d05-preserve').status,'new');for(const n of nodes)act(n.id);assert.equal(earnedAchievements(pack,flags).length,2);const before=flags.size;for(const n of nodes)assert.equal(act(n.id).status,'repeat');assert.equal(flags.size,before);assert.equal(nodes.filter(n=>n.reward&&flags.has(n.id)).length,5);for(const a of pack.achievements)for(const id of a.requires){const less=new Set(flags);less.delete(id);assert.ok(!earnedAchievements(pack,less).some(x=>x.id===a.id));}});
const report={day:5,counts:{outside:3,inside:10,rewards:5,photos:2,achievements:2,animals:1},sourceSha256:createHash('sha256').update(readFileSync('design/exploration-014/day05/river-teahouse-source.png')).digest('hex'),results};
writeFileSync('design/exploration-014/day05/audit-results.json',JSON.stringify(report,null,2)+'\n');
for(const r of results)console.log(r.status,r.name,r.error??'');
if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
